<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AdminMenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('admin_menus')->delete();
        
        \DB::table('admin_menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => 0,
                'custom_order' => 0,
                'title' => '控制台',
                'icon' => 'mdi:chart-line',
                'url' => '/dashboard',
                'url_type' => 1,
                'visible' => 0,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-04 00:47:12',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            1 => 
            array (
                'id' => 2,
                'parent_id' => 0,
                'custom_order' => 99999,
                'title' => '系统管理',
                'icon' => 'material-symbols:settings-outline',
                'url' => '/system',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-04 00:47:12',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            2 => 
            array (
                'id' => 3,
                'parent_id' => 2,
                'custom_order' => 0,
                'title' => 'admin_users',
                'icon' => 'ph:user-gear',
                'url' => '/system/admin_users',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-04 00:47:12',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            3 => 
            array (
                'id' => 4,
                'parent_id' => 2,
                'custom_order' => 0,
                'title' => 'admin_roles',
                'icon' => 'carbon:user-role',
                'url' => '/system/admin_roles',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-04 00:47:12',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            4 => 
            array (
                'id' => 5,
                'parent_id' => 2,
                'custom_order' => 0,
                'title' => 'admin_permission',
                'icon' => 'fluent-mdl2:permissions',
                'url' => '/system/admin_permissions',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-04 00:47:12',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            5 => 
            array (
                'id' => 6,
                'parent_id' => 2,
                'custom_order' => 0,
                'title' => 'admin_menu',
                'icon' => 'ant-design:menu-unfold-outlined',
                'url' => '/system/admin_menus',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-04 00:47:12',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            6 => 
            array (
                'id' => 7,
                'parent_id' => 2,
                'custom_order' => 0,
                'title' => 'admin_setting',
                'icon' => 'akar-icons:settings-horizontal',
                'url' => '/system/settings',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-04 00:47:12',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            7 => 
            array (
                'id' => 8,
                'parent_id' => 0,
                'custom_order' => 0,
                'title' => '应用设置',
                'icon' => 'ant-design:appstore-filled',
                'url' => '/app',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => 0,
                'iframe_url' => NULL,
                'component' => 'amis',
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-04 01:25:48',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            8 => 
            array (
                'id' => 10,
                'parent_id' => 8,
                'custom_order' => 100,
                'title' => '应用管理',
                'icon' => 'ant-design:appstore-filled',
                'url' => '/apps',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-04 01:30:27',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            9 => 
            array (
                'id' => 11,
                'parent_id' => 8,
                'custom_order' => 100,
                'title' => '分类管理',
                'icon' => 'ic:round-category',
                'url' => '/categories',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-04 01:32:45',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            10 => 
            array (
                'id' => 12,
                'parent_id' => 8,
                'custom_order' => 100,
                'title' => '标签管理',
                'icon' => 'ant-design:tags-filled',
                'url' => '/tags',
                'url_type' => 1,
                'visible' => 0,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-04 01:33:16',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            11 => 
            array (
                'id' => 13,
                'parent_id' => 8,
                'custom_order' => 100,
                'title' => '智能体设置',
                'icon' => 'simple-icons:powervirtualagents',
                'url' => '/agents',
                'url_type' => 1,
                'visible' => 0,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-04 01:34:39',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            12 => 
            array (
                'id' => 14,
                'parent_id' => 0,
                'custom_order' => 103,
                'title' => '算力管理',
                'icon' => 'academicons:crossref-square',
                'url' => '/compute_powers',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-04 01:35:27',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            13 => 
            array (
                'id' => 15,
                'parent_id' => 26,
                'custom_order' => 100,
                'title' => '轮播图管理',
                'icon' => 'material-symbols-light:planner-banner-ad-pt',
                'url' => '/banners',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-05 02:24:57',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            14 => 
            array (
                'id' => 16,
                'parent_id' => 8,
                'custom_order' => 100,
                'title' => '魔方管理',
                'icon' => 'gravity-ui:cubes-3-overlap',
                'url' => '/cubes',
                'url_type' => 1,
                'visible' => 0,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-07 00:50:11',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            15 => 
            array (
                'id' => 17,
                'parent_id' => 28,
                'custom_order' => 101,
                'title' => '订单管理',
                'icon' => 'ant-design:pay-circle-filled',
                'url' => '/orders',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-08 09:14:32',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            16 => 
            array (
                'id' => 18,
                'parent_id' => 0,
                'custom_order' => 102,
                'title' => '会员管理',
                'icon' => 'icon-park-twotone:vip-one',
                'url' => '/vips',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-19 02:52:54',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            17 => 
            array (
                'id' => 19,
                'parent_id' => 0,
                'custom_order' => 100,
                'title' => '商户管理',
                'icon' => 'mingcute:vip-2-fill',
                'url' => '/mchs',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-21 07:08:21',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            18 => 
            array (
                'id' => 21,
                'parent_id' => 0,
                'custom_order' => 200,
                'title' => '用户管理',
                'icon' => 'carbon:user-avatar-filled',
                'url' => '/users',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 1,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-22 00:14:29',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            19 => 
            array (
                'id' => 22,
                'parent_id' => 26,
                'custom_order' => 100,
                'title' => '卡密管理',
                'icon' => 'ant-design:code-filled',
                'url' => '/codes',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-22 01:56:06',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            20 => 
            array (
                'id' => 23,
                'parent_id' => 26,
                'custom_order' => 100,
                'title' => '分销管理',
                'icon' => 'bxs:spreadsheet',
                'url' => '/spreads',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-24 13:47:29',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            21 => 
            array (
                'id' => 24,
                'parent_id' => 0,
                'custom_order' => 100,
                'title' => '文件上传日志',
                'icon' => 'ph:circle',
                'url' => '/upload_imgs',
                'url_type' => 1,
                'visible' => 0,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-24 14:01:03',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            22 => 
            array (
                'id' => 25,
                'parent_id' => 8,
                'custom_order' => 100,
                'title' => '扣子空间',
                'icon' => 'f7:doc-append',
                'url' => '/konts',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-25 00:16:14',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            23 => 
            array (
                'id' => 26,
                'parent_id' => 0,
                'custom_order' => 105,
                'title' => '营销管理',
                'icon' => 'icon-park-solid:sales-report',
                'url' => '/yingxiao',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => 0,
                'iframe_url' => NULL,
                'component' => 'amis',
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-25 01:05:11',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            24 => 
            array (
                'id' => 27,
                'parent_id' => 28,
                'custom_order' => 100,
                'title' => '算力使用',
                'icon' => 'flowbite:rectangle-list-solid',
                'url' => '/power_deduction_logs',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => NULL,
                'iframe_url' => NULL,
                'component' => NULL,
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-26 16:40:26',
                'updated_at' => '2025-11-29 01:12:39',
            ),
            25 => 
            array (
                'id' => 28,
                'parent_id' => 0,
                'custom_order' => 200,
                'title' => '订单管理',
                'icon' => 'fluent:image-border-24-filled',
                'url' => '/order',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'keep_alive' => 0,
                'iframe_url' => NULL,
                'component' => 'amis',
                'is_full' => 0,
                'extension' => NULL,
                'created_at' => '2025-11-29 01:02:12',
                'updated_at' => '2025-11-29 01:12:39',
            ),
        ));
        
        
    }
}