<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AdminCodeGeneratorsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('admin_code_generators')->delete();
        
        \DB::table('admin_code_generators')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => '分类管理',
                'table_name' => 'categories',
                'primary_key' => 'id',
                'model_name' => 'App/Models/Categorie',
                'controller_name' => 'App/Admin/Controllers/CategorieController',
                'service_name' => 'App/Services/CategorieService',
                'columns' => '[{"name":"name","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u5206\\u7c7b\\u540d\\u79f0","generation":null},{"name":"icon","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":true,"default":null,"auto_increment":false,"comment":"\\u5206\\u7c7b\\u56fe\\u6807URL","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"parent_id":8,"icon":"ic:round-category","title":"\\u5206\\u7c7b\\u7ba1\\u7406","route":"\\/categories"}',
                'page_info' => '{"dialog_form":"dialog","row_actions":["create","show","edit","delete","batch_delete"],"dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-04 01:26:22',
                'updated_at' => '2025-11-04 01:32:28',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => '标签管理',
                'table_name' => 'tags',
                'primary_key' => 'id',
                'model_name' => 'App/Models/Tag',
                'controller_name' => 'App/Admin/Controllers/TagController',
                'service_name' => 'App/Services/TagService',
                'columns' => '[{"name":"name","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u6807\\u7b7e\\u540d\\u79f0","generation":null},{"name":"background_color","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":true,"default":null,"auto_increment":false,"comment":"\\u6807\\u7b7e\\u80cc\\u666f\\u8272","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"parent_id":8,"icon":"ant-design:tags-filled","title":"\\u6807\\u7b7e\\u7ba1\\u7406","route":"\\/tags"}',
                'page_info' => '{"dialog_form":"dialog","row_actions":["create","show","edit","delete","batch_delete"],"dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-04 01:26:39',
                'updated_at' => '2025-11-04 01:33:13',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => '应用设置',
                'table_name' => 'apps',
                'primary_key' => 'id',
                'model_name' => 'App/Models/App',
                'controller_name' => 'App/Admin/Controllers/AppController',
                'service_name' => 'App/Services/AppService',
                'columns' => '[{"name":"name","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u5e94\\u7528\\u540d\\u79f0","generation":null},{"name":"description","type_name":"text","type":"text","collation":"utf8mb4_0900_ai_ci","nullable":true,"default":null,"auto_increment":false,"comment":"\\u5e94\\u7528\\u63cf\\u8ff0","generation":null},{"name":"opening_remark","type_name":"text","type":"text","collation":"utf8mb4_0900_ai_ci","nullable":true,"default":null,"auto_increment":false,"comment":"\\u5f00\\u573a\\u767d","generation":null},{"name":"category_id","type_name":"int","type":"integer","collation":null,"nullable":true,"default":null,"auto_increment":false,"comment":"CategoryId","generation":null},{"name":"comfyui_workflow_params","type_name":"json","type":"json","collation":null,"nullable":true,"default":null,"auto_increment":false,"comment":"ComfyUI \\u5de5\\u4f5c\\u6d41\\u53c2\\u6570","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"parent_id":8,"icon":null,"title":"\\u5e94\\u7528\\u8bbe\\u7f6e","route":"\\/apps"}',
                'page_info' => '{"dialog_form":"dialog","row_actions":["create","show","edit","delete","batch_delete"],"dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-04 01:26:59',
                'updated_at' => '2025-11-04 01:30:50',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => '智能体设置',
                'table_name' => 'agents',
                'primary_key' => 'id',
                'model_name' => 'App/Models/Agent',
                'controller_name' => 'App/Admin/Controllers/AgentController',
                'service_name' => 'App/Services/AgentService',
                'columns' => '[{"name":"name","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u667a\\u80fd\\u4f53\\u540d\\u79f0","generation":null},{"name":"icon","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":true,"default":null,"auto_increment":false,"comment":"\\u56fe\\u6807URL","generation":null},{"name":"introduction","type_name":"text","type":"text","collation":"utf8mb4_0900_ai_ci","nullable":true,"default":null,"auto_increment":false,"comment":"\\u4ecb\\u7ecd","generation":null},{"name":"opening_remark","type_name":"text","type":"text","collation":"utf8mb4_0900_ai_ci","nullable":true,"default":null,"auto_increment":false,"comment":"\\u5f00\\u573a\\u767d","generation":null},{"name":"prompt_settings","type_name":"text","type":"text","collation":"utf8mb4_0900_ai_ci","nullable":true,"default":null,"auto_increment":false,"comment":"\\u63d0\\u793a\\u8bcd\\u8bbe\\u7f6e","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"parent_id":8,"icon":"simple-icons:powervirtualagents","title":"\\u667a\\u80fd\\u4f53\\u8bbe\\u7f6e","route":"\\/agents"}',
                'page_info' => '{"dialog_form":"dialog","row_actions":["create","show","edit","delete","batch_delete"],"dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-04 01:27:19',
                'updated_at' => '2025-11-04 01:34:27',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => '算力管理',
                'table_name' => 'compute_powers',
                'primary_key' => 'id',
                'model_name' => 'App/Models/ComputePower',
                'controller_name' => 'App/Admin/Controllers/ComputePowerController',
                'service_name' => 'App/Services/ComputePowerService',
                'columns' => '[{"name":"name","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u5957\\u9910\\u540d\\u79f0","generation":null},{"name":"power_value","type_name":"int","type":"integer","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"\\u7b97\\u529b\\u503c","generation":null},{"name":"amount","type_name":"decimal","type":"decimal","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"\\u91d1\\u989d","generation":null},{"name":"description","type_name":"text","type":"text","collation":"utf8mb4_0900_ai_ci","nullable":true,"default":null,"auto_increment":false,"comment":"\\u7b97\\u529b\\u4ecb\\u7ecd","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"parent_id":0,"icon":"academicons:crossref-square","title":"\\u7b97\\u529b\\u7ba1\\u7406","route":"\\/compute_powers"}',
                'page_info' => '{"dialog_form":"dialog","row_actions":["create","show","edit","delete","batch_delete"],"dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-04 01:28:02',
                'updated_at' => '2025-11-04 01:31:49',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => '轮播图管理',
                'table_name' => 'banners',
                'primary_key' => 'id',
                'model_name' => 'App/Models/Banner',
                'controller_name' => 'App/Admin/Controllers/BannerController',
                'service_name' => 'App/Services/BannerService',
                'columns' => '[{"name":"name","type_name":"varchar","type":"string","collation":"utf8mb3_general_ci","nullable":true,"default":null,"auto_increment":false,"comment":"Name","generation":null},{"name":"path","type_name":"varchar","type":"string","collation":"utf8mb3_general_ci","nullable":true,"default":null,"auto_increment":false,"comment":"Path","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"parent_id":0,"icon":"material-symbols-light:planner-banner-ad-pt","title":"\\u8f6e\\u64ad\\u56fe\\u7ba1\\u7406","route":"\\/banners"}',
                'page_info' => '{"dialog_form":"dialog","row_actions":["create","show","edit","delete","batch_delete"],"dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-05 02:24:06',
                'updated_at' => '2025-11-05 02:24:47',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => '魔方管理',
                'table_name' => 'cubes',
                'primary_key' => 'id',
                'model_name' => 'App/Models/Cube',
                'controller_name' => 'App/Admin/Controllers/CubeController',
                'service_name' => 'App/Services/CubeService',
                'columns' => '[{"name":"name","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u9b54\\u65b9\\u540d\\u79f0","generation":null},{"name":"icon","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":true,"default":null,"auto_increment":false,"comment":"\\u9b54\\u65b9\\u56fe\\u6807URL","generation":null},{"name":"sort","type_name":"int","type":"integer","collation":null,"nullable":true,"default":"0","auto_increment":false,"comment":"\\u6392\\u5e8f","generation":null},{"name":"is_status","type_name":"tinyint","type":"tinyInteger","collation":null,"nullable":true,"default":"1","auto_increment":false,"comment":"\\u72b6\\u6001","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"parent_id":0,"icon":"ph:circle","title":"\\u9b54\\u65b9\\u7ba1\\u7406","route":"\\/cubes"}',
                'page_info' => '{"row_actions":["create","show","edit","delete","batch_delete"],"dialog_form":"dialog","dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-07 00:50:05',
                'updated_at' => '2025-11-07 00:50:05',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => '订单记录',
                'table_name' => 'orders',
                'primary_key' => 'id',
                'model_name' => 'App/Models/Order',
                'controller_name' => 'App/Admin/Controllers/OrderController',
                'service_name' => 'App/Services/OrderService',
            'columns' => '[{"name":"user_id","type_name":"int","type":"integer","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"\\u7528\\u6237ID (\\u5047\\u8bbe\\u5b58\\u5728 users \\u8868)","generation":null},{"name":"name","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u5145\\u503c\\u540d\\u79f0","generation":null},{"name":"amount","type_name":"decimal","type":"decimal","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"\\u5145\\u503c\\u91d1\\u989d","generation":null},{"name":"order_no","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u8ba2\\u5355\\u53f7","generation":null},{"name":"invoiced","type_name":"tinyint","type":"tinyInteger","collation":null,"nullable":false,"default":"0","auto_increment":false,"comment":"\\u662f\\u5426\\u5f00\\u7968","generation":null},{"name":"order_type","type_name":"tinyint","type":"tinyInteger","collation":null,"nullable":false,"default":"1","auto_increment":false,"comment":"1\\u662f\\u7b97\\u529b\\u8ba2\\u5355\\uff0c2\\u4f1a\\u5458\\u8ba2\\u5355","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"parent_id":0,"icon":"ant-design:pay-circle-filled","title":"\\u8ba2\\u5355\\u8bb0\\u5f55","route":"\\/orders"}',
                'page_info' => '{"row_actions":["create","show","edit","delete","batch_delete"],"dialog_form":"dialog","dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-08 09:13:53',
                'updated_at' => '2025-11-08 09:14:29',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => '会员管理',
                'table_name' => 'vips',
                'primary_key' => 'id',
                'model_name' => 'App/Models/Vip',
                'controller_name' => 'App/Admin/Controllers/VipController',
                'service_name' => 'App/Services/VipService',
                'columns' => '[{"name":"name","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u5957\\u9910\\u540d\\u79f0","generation":null},{"name":"amount","type_name":"decimal","type":"decimal","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"\\u91d1\\u989d","generation":null},{"name":"description","type_name":"text","type":"text","collation":"utf8mb4_0900_ai_ci","nullable":true,"default":null,"auto_increment":false,"comment":"\\u4f1a\\u5458\\u4ecb\\u7ecd","generation":null},{"name":"is_status","type_name":"tinyint","type":"tinyInteger","collation":null,"nullable":true,"default":"1","auto_increment":false,"comment":"\\u72b6\\u6001","generation":null},{"name":"sort","type_name":"int","type":"integer","collation":null,"nullable":true,"default":"0","auto_increment":false,"comment":"\\u6392\\u5e8f","generation":null},{"name":"power_value","type_name":"int","type":"integer","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"\\u8d60\\u9001\\u7b97\\u529b\\u503c","generation":null},{"name":"day_number","type_name":"int","type":"integer","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"\\u6709\\u6548\\u5929\\u6570","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"parent_id":0,"icon":"ph:circle","route":"\\/vips","title":"\\u4f1a\\u5458\\u7ba1\\u7406"}',
                'page_info' => '{"dialog_form":"dialog","row_actions":["create","show","edit","delete","batch_delete"],"dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-19 02:52:43',
                'updated_at' => '2025-11-19 02:52:43',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => '商户管理',
                'table_name' => 'mchs',
                'primary_key' => 'id',
                'model_name' => 'App/Models/Mch',
                'controller_name' => 'App/Admin/Controllers/MchController',
                'service_name' => 'App/Services/MchService',
                'columns' => '[{"name":"is_h5","type_name":"tinyint","type":"tinyInteger","collation":null,"nullable":true,"default":"0","auto_increment":false,"comment":"IsH5","generation":null},{"name":"is_mini","type_name":"tinyint","type":"tinyInteger","collation":null,"nullable":true,"default":"0","auto_increment":false,"comment":"IsMini","generation":null},{"name":"is_pc","type_name":"tinyint","type":"tinyInteger","collation":null,"nullable":true,"default":"0","auto_increment":false,"comment":"IsPc","generation":null},{"name":"is_status","type_name":"tinyint","type":"tinyInteger","collation":null,"nullable":true,"default":"1","auto_increment":false,"comment":"IsStatus","generation":null},{"name":"logo","type_name":"varchar","type":"string","collation":"utf8mb3_general_ci","nullable":true,"default":null,"auto_increment":false,"comment":"Logo","generation":null},{"name":"mini_config","type_name":"text","type":"text","collation":"utf8mb3_general_ci","nullable":true,"default":null,"auto_increment":false,"comment":"MiniConfig","generation":null},{"name":"name","type_name":"varchar","type":"string","collation":"utf8mb3_general_ci","nullable":true,"default":null,"auto_increment":false,"comment":"Name","generation":null},{"name":"remark","type_name":"varchar","type":"string","collation":"utf8mb3_general_ci","nullable":true,"default":null,"auto_increment":false,"comment":"Remark","generation":null},{"name":"service_at","type_name":"varchar","type":"string","collation":"utf8mb3_general_ci","nullable":true,"default":null,"auto_increment":false,"comment":"ServiceAt","generation":null},{"name":"web_config","type_name":"text","type":"text","collation":"utf8mb3_general_ci","nullable":true,"default":null,"auto_increment":false,"comment":"WebConfig","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"parent_id":0,"icon":"ph:circle","title":"\\u5546\\u6237\\u7ba1\\u7406","route":"\\/mchs"}',
                'page_info' => '{"row_actions":["create","show","edit","delete","batch_delete"],"dialog_form":"dialog","dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-21 07:08:17',
                'updated_at' => '2025-11-21 07:08:17',
            ),
            10 => 
            array (
                'id' => 12,
                'title' => '用户管理',
                'table_name' => 'users',
                'primary_key' => 'id',
                'model_name' => 'App/Models/User',
                'controller_name' => 'App/Admin/Controllers/UserController',
                'service_name' => 'App/Services/UserService',
                'columns' => '[{"name":"ask_id","type_name":"int","type":"integer","collation":null,"nullable":true,"default":null,"auto_increment":false,"comment":"AskId","generation":null},{"name":"invite_count","type_name":"int","type":"integer","collation":null,"nullable":true,"default":"0","auto_increment":false,"comment":"InviteCount","generation":null},{"name":"is_status","type_name":"tinyint","type":"tinyInteger","collation":null,"nullable":true,"default":"1","auto_increment":false,"comment":"IsStatus","generation":null},{"name":"mch_id","type_name":"int","type":"integer","collation":null,"nullable":true,"default":null,"auto_increment":false,"comment":"MchId","generation":null},{"name":"name","type_name":"varchar","type":"string","collation":"utf8mb4_unicode_ci","nullable":false,"default":null,"auto_increment":false,"comment":"Name","generation":null},{"name":"openid","type_name":"varchar","type":"string","collation":"utf8mb4_unicode_ci","nullable":true,"default":null,"auto_increment":false,"comment":"Openid","generation":null},{"name":"phone","type_name":"varchar","type":"string","collation":"utf8mb4_unicode_ci","nullable":true,"default":null,"auto_increment":false,"comment":"Phone","generation":null},{"name":"power_value","type_name":"decimal","type":"decimal","collation":null,"nullable":true,"default":"0.00","auto_increment":false,"comment":"PowerValue","generation":null},{"name":"remember_token","type_name":"varchar","type":"string","collation":"utf8mb4_unicode_ci","nullable":true,"default":null,"auto_increment":false,"comment":"RememberToken","generation":null},{"name":"sign_at","type_name":"varchar","type":"string","collation":"utf8mb4_unicode_ci","nullable":true,"default":null,"auto_increment":false,"comment":"SignAt","generation":null},{"name":"vip_expire_time","type_name":"date","type":"date","collation":null,"nullable":true,"default":null,"auto_increment":false,"comment":"\\u4f1a\\u5458\\u8fc7\\u671f\\u65f6\\u95f4","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"parent_id":0,"icon":"ph:circle","title":"\\u7528\\u6237\\u7ba1\\u7406","route":"\\/users"}',
                'page_info' => '{"dialog_form":"dialog","row_actions":["create","show","edit","delete","batch_delete"],"dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-22 00:13:54',
                'updated_at' => '2025-11-22 00:14:21',
            ),
            11 => 
            array (
                'id' => 13,
                'title' => '卡密管理',
                'table_name' => 'codes',
                'primary_key' => 'id',
                'model_name' => 'App/Models/Code',
                'controller_name' => 'App/Admin/Controllers/CodeController',
                'service_name' => 'App/Services/CodeService',
                'columns' => '[{"name":"code","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":true,"default":null,"auto_increment":false,"comment":"\\u5361\\u5bc6","generation":null},{"name":"code_type","type_name":"tinyint","type":"tinyInteger","collation":null,"nullable":true,"default":"1","auto_increment":false,"comment":"\\u7c7b\\u578b1\\u7b97\\u529b\\uff0c2\\u4f1a\\u5458","generation":null},{"name":"is_status","type_name":"tinyint","type":"tinyInteger","collation":null,"nullable":true,"default":"1","auto_increment":false,"comment":"\\u72b6\\u6001","generation":null},{"name":"mch_id","type_name":"int","type":"integer","collation":null,"nullable":true,"default":null,"auto_increment":false,"comment":"MchId","generation":null},{"name":"name","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u751f\\u6210\\u540d\\u79f0","generation":null},{"name":"user_id","type_name":"int","type":"integer","collation":null,"nullable":true,"default":null,"auto_increment":false,"comment":"UserId","generation":null},{"name":"value","type_name":"int","type":"integer","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"\\u91d1\\u989d","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_database_migration","need_create_table","need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"icon":"ph:circle","parent_id":0,"title":"\\u5361\\u5bc6\\u7ba1\\u7406","route":"\\/codes"}',
                'page_info' => '{"dialog_form":"dialog","row_actions":["create","show","edit","delete","batch_delete"],"dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-22 01:56:01',
                'updated_at' => '2025-11-22 01:56:01',
            ),
            12 => 
            array (
                'id' => 14,
                'title' => '推广记录',
                'table_name' => 'spreads',
                'primary_key' => 'id',
                'model_name' => 'App/Models/Spread',
                'controller_name' => 'App/Admin/Controllers/SpreadController',
                'service_name' => 'App/Services/SpreadService',
                'columns' => '[{"name":"amount","type_name":"int","type":"integer","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"\\u5206\\u6210","generation":null},{"name":"tg_user_id","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u63a8\\u5e7f\\u4eba","generation":null},{"name":"user_id","type_name":"int","type":"integer","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"\\u63a8\\u5e7f\\u5458ID","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_database_migration","need_create_table","need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"icon":"ph:circle","parent_id":0,"title":"\\u63a8\\u5e7f\\u8bb0\\u5f55","route":"\\/spreads"}',
                'page_info' => '{"dialog_form":"dialog","row_actions":["create","show","edit","delete","batch_delete"],"dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-24 13:46:46',
                'updated_at' => '2025-11-24 13:46:46',
            ),
            13 => 
            array (
                'id' => 15,
                'title' => '文件上传日志',
                'table_name' => 'upload_imgs',
                'primary_key' => 'id',
                'model_name' => 'App/Models/UploadImg',
                'controller_name' => 'App/Admin/Controllers/UploadImgController',
                'service_name' => 'App/Services/UploadImgService',
                'columns' => '[{"name":"file","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":"0.00","auto_increment":false,"comment":"\\u5206\\u6210","generation":null},{"name":"mch_id","type_name":"int","type":"integer","collation":null,"nullable":true,"default":null,"auto_increment":false,"comment":"\\u5546\\u6237ID","generation":null},{"name":"url","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u63a8\\u5e7f\\u4eba","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_controller","need_service","need_database_migration"]',
                'menu_info' => '{"enabled":1,"parent_id":0,"icon":"ph:circle","title":"\\u6587\\u4ef6\\u4e0a\\u4f20\\u65e5\\u5fd7","route":"\\/upload_imgs"}',
                'page_info' => '{"dialog_form":"dialog","row_actions":["create","show","edit","delete","batch_delete"],"dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-24 14:00:46',
                'updated_at' => '2025-11-24 14:00:46',
            ),
            14 => 
            array (
                'id' => 16,
                'title' => '扣子设置',
                'table_name' => 'konts',
                'primary_key' => 'id',
                'model_name' => 'App/Models/Kont',
                'controller_name' => 'App/Admin/Controllers/KontController',
                'service_name' => 'App/Services/KontService',
                'columns' => '[{"name":"agent_id","type_name":"int","type":"integer","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"\\u4ee3\\u7406ID","generation":null},{"name":"app_id","type_name":"varchar","type":"string","collation":"utf8mb4_general_ci","nullable":false,"default":null,"auto_increment":false,"comment":"appid","generation":null},{"name":"app_key","type_name":"text","type":"text","collation":"utf8mb4_general_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u79c1\\u94a5\\u8bc1\\u4e66","generation":null},{"name":"app_secret","type_name":"varchar","type":"string","collation":"utf8mb4_general_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u516c\\u94a5","generation":null},{"name":"is_status","type_name":"int","type":"integer","collation":null,"nullable":true,"default":"1","auto_increment":false,"comment":"IsStatus","generation":null},{"name":"mch_id","type_name":"int","type":"integer","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"MchId","generation":null},{"name":"name","type_name":"varchar","type":"string","collation":"utf8mb4_general_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u7a7a\\u95f4\\u540d\\u79f0","generation":null},{"name":"space_id","type_name":"varchar","type":"string","collation":"utf8mb4_general_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u6263\\u5b50\\u7a7a\\u95f4ID","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"parent_id":0,"icon":"ph:circle","title":"\\u6263\\u5b50\\u8bbe\\u7f6e","route":"\\/konts"}',
                'page_info' => '{"dialog_form":"dialog","row_actions":["create","show","edit","delete","batch_delete"],"dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-25 00:16:09',
                'updated_at' => '2025-11-25 00:16:09',
            ),
            15 => 
            array (
                'id' => 17,
                'title' => '扣子token日志',
                'table_name' => 'kont_tokens',
                'primary_key' => 'id',
                'model_name' => 'App/Models/KontToken',
                'controller_name' => 'App/Admin/Controllers/KontTokenController',
                'service_name' => 'App/Services/KontTokenService',
                'columns' => '[{"name":"app_id","type_name":"varchar","type":"string","collation":"utf8mb3_general_ci","nullable":false,"default":null,"auto_increment":false,"comment":"AppId","generation":null},{"name":"expires_in","type_name":"int","type":"integer","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"ExpiresIn","generation":null},{"name":"token","type_name":"varchar","type":"string","collation":"utf8mb3_general_ci","nullable":false,"default":null,"auto_increment":false,"comment":"Token","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 1,
                'needs' => '["need_model"]',
                'menu_info' => '{"enabled":false,"parent_id":0,"icon":"ph:circle","title":"\\u6263\\u5b50token\\u65e5\\u5fd7","route":"\\/kont_tokens"}',
                'page_info' => '{"dialog_form":"dialog","row_actions":["create","show","edit","delete","batch_delete"],"dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-25 00:43:03',
                'updated_at' => '2025-11-25 00:43:03',
            ),
            16 => 
            array (
                'id' => 18,
                'title' => '对话记录',
                'table_name' => 'app_logs',
                'primary_key' => 'id',
                'model_name' => 'App/Models/AppLog',
                'controller_name' => 'App/Admin/Controllers/AppLogController',
                'service_name' => 'App/Services/AppLogService',
                'columns' => '[{"name":"contents","type_name":"mediumtext","type":"mediumText","collation":"utf8mb4_general_ci","nullable":true,"default":null,"auto_increment":false,"comment":"Contents","generation":null},{"name":"icon_url","type_name":"varchar","type":"string","collation":"utf8mb4_general_ci","nullable":true,"default":null,"auto_increment":false,"comment":"IconUrl","generation":null},{"name":"is_status","type_name":"tinyint","type":"tinyInteger","collation":null,"nullable":true,"default":"1","auto_increment":false,"comment":"IsStatus","generation":null},{"name":"log_type","type_name":"varchar","type":"string","collation":"utf8mb4_general_ci","nullable":true,"default":null,"auto_increment":false,"comment":"LogType","generation":null},{"name":"mch_id","type_name":"int","type":"integer","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"\\u5546\\u6237iD","generation":null},{"name":"name","type_name":"varchar","type":"string","collation":"utf8mb4_general_ci","nullable":true,"default":null,"auto_increment":false,"comment":"\\u5206\\u7ec4\\u540d\\u79f0","generation":null},{"name":"pid","type_name":"int","type":"integer","collation":null,"nullable":true,"default":null,"auto_increment":false,"comment":"Pid","generation":null},{"name":"user_id","type_name":"int","type":"integer","collation":null,"nullable":true,"default":null,"auto_increment":false,"comment":"UserId","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_model"]',
                'menu_info' => '{"enabled":false,"parent_id":0,"icon":"ph:circle","title":"\\u5bf9\\u8bdd\\u8bb0\\u5f55","route":"\\/app_logs"}',
                'page_info' => '{"dialog_form":"dialog","row_actions":["create","show","edit","delete","batch_delete"],"dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-26 02:16:25',
                'updated_at' => '2025-11-26 02:16:25',
            ),
            17 => 
            array (
                'id' => 19,
                'title' => '算力使用记录',
                'table_name' => 'power_deduction_logs',
                'primary_key' => 'id',
                'model_name' => 'App/Models/PowerDeductionLog',
                'controller_name' => 'App/Admin/Controllers/PowerDeductionLogController',
                'service_name' => 'App/Services/PowerDeductionLogService',
            'columns' => '[{"name":"deduction_name","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u6263\\u70b9\\u540d\\u79f0","generation":null},{"name":"deduction_type","type_name":"varchar","type":"string","collation":"utf8mb4_0900_ai_ci","nullable":false,"default":null,"auto_increment":false,"comment":"\\u6263\\u70b9\\u7c7b\\u578b","generation":null},{"name":"power_value","type_name":"int","type":"integer","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"\\u6263\\u9664\\u7b97\\u529b\\u503c","generation":null},{"name":"user_id","type_name":"int","type":"integer","collation":null,"nullable":false,"default":null,"auto_increment":false,"comment":"\\u7528\\u6237ID (\\u5047\\u8bbe\\u5b58\\u5728 users \\u8868)","generation":null}]',
                'need_timestamps' => 1,
                'soft_delete' => 0,
                'needs' => '["need_model","need_controller","need_service"]',
                'menu_info' => '{"enabled":1,"parent_id":0,"icon":"flowbite:rectangle-list-solid","route":"\\/power_deduction_logs","title":"\\u7b97\\u529b\\u4f7f\\u7528\\u8bb0\\u5f55"}',
                'page_info' => '{"row_actions":["create","show","edit","delete","batch_delete"],"dialog_form":"dialog","dialog_size":"md","list_display_created_at":1,"list_display_updated_at":1}',
                'created_at' => '2025-11-26 16:39:38',
                'updated_at' => '2025-11-26 16:40:23',
            ),
        ));
        
        
    }
}