<?php

// =====================================================================

// !!  路由文件由 owl-admin 自动生成，请不要手动修改。

// !!  Route file auto generated by owl-admin, don't modify it manually.

// =====================================================================

use Slowlyo\OwlAdmin\Admin;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Route;

Route::group([
    'domain'     => Admin::config('admin.route.domain'),
    'prefix'     => Admin::config('admin.route.prefix'),
    'middleware' => Admin::config('admin.route.middleware'),
], function (Router $router) {
    // 分类管理
    $router->resource('categories', \App\Admin\Controllers\CategorieController::class);
    // 标签管理
    $router->resource('tags', \App\Admin\Controllers\TagController::class);
    // 应用设置
    $router->resource('apps', \App\Admin\Controllers\AppController::class);
    // 智能体设置
    $router->resource('agents', \App\Admin\Controllers\AgentController::class);
    // 算力管理
    $router->resource('compute_powers', \App\Admin\Controllers\ComputePowerController::class);
    // 轮播图管理
    $router->resource('banners', \App\Admin\Controllers\BannerController::class);
    // 魔方管理
    $router->resource('cubes', \App\Admin\Controllers\CubeController::class);
    // 订单记录
    $router->resource('orders', \App\Admin\Controllers\OrderController::class);
    // 会员管理
    $router->resource('vips', \App\Admin\Controllers\VipController::class);
    // 商户管理
    $router->resource('mchs', \App\Admin\Controllers\MchController::class);
    // 用户管理
    $router->resource('users', \App\Admin\Controllers\UserController::class);
    // 卡密管理
    $router->resource('codes', \App\Admin\Controllers\CodeController::class);
    // 推广记录
    $router->resource('spreads', \App\Admin\Controllers\SpreadController::class);
    // 文件上传日志
    $router->resource('upload_imgs', \App\Admin\Controllers\UploadImgController::class);
    // 扣子设置
    $router->resource('konts', \App\Admin\Controllers\KontController::class);
    // 算力使用记录
    $router->resource('power_deduction_logs', \App\Admin\Controllers\PowerDeductionLogController::class);
    // 分类列表
    $router->get('select_categorie_options', [\Slowlyo\OwlAdmin\Controllers\AdminApiController::class, 'index']);
    // 商户列表
    $router->get('select_mch_options', [\Slowlyo\OwlAdmin\Controllers\AdminApiController::class, 'index']);
    // 扣子空间
    $router->get('select_kont_options', [\Slowlyo\OwlAdmin\Controllers\AdminApiController::class, 'index']);

});